# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [juanma386]
liberapay: # Replace with a single Liberapay yuma2020
Team Hexome: # Replace with up to 4 custom sponsorship URLs e.g., ['hexome.cloud', 'hexomedesarrollos.com']
